from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Callable, Sequence

from testahedron.axes import optionals, platforms, pythons
from testahedron.matrix import Axis, Matrix


@dataclass
class Task:
    """
    A thing to do; the implicit axis of:

    - tests
    - api docs
    - narrative docs
    - release: build, publish
    """

    shellCommands: list[str]  # probably too simple (???)
    needs: list[Task]  # the tasks which much complete before this one


@dataclass
class DependencyConstraints:
    """
    List of dependency constraints, drawn from a lockfile of some kind,
    intended to provide a range of options for suppoprting older versions of
    other dependencies.  i.e. (no word for it yet)/mindeps axis
    """

    versions: list[str]


@dataclass
class DepGroups:
    """
    A set of dependency groups to install, i.e. alldeps/nodeps axis.
    """

    groups: list[str]


@dataclass
class HasCoverage:
    """
    Does this job have coverage?  Not just a bool because we're going to need
    methods on here to compute some extra shell commands at the beginning / end
    of the job.
    """

    hasCoverage: bool


@dataclass
class HasIPv6:
    """
    Does the job run in an environment that has IPv6 connectivity?  Needed to
    contribute some sysctl commands to the setup process.
    """

    hasIPv6: bool


@dataclass
class Job:
    system: platforms.SystemType
    python: pythons.PythonVersion
    task: Task
    dependencyConstraints: DependencyConstraints
    optionalDependencyGroupSets: DepGroups
    coverage: HasCoverage  # include coverage? withcov/nocov axis


matrix = Matrix(
    [
        platforms.os,
        pythons.pythonVersions,
        optionals.getExtras(),
        Axis(
            "reactor",
            [
                # this needs to be restricted to the platforms.os axis
                # having a value of SystemType.windows
                "iocp",
                "select",
                # this needs to be restricted to the platform.os axis having a
                # value of SystemType.linux (maybe?) and "platform-deps" having
                # "gtk-platform" (definitely)
                "gi",
            ],
        ),
        Axis(
            "platform-deps",
            [
                None,
                "gtk-platform",
                # what if there are multiple platform deps that might be
                # installed in any configuration???
            ],
        ),
    ]
)


@dataclass
class Providence:
    """
    Because environmental dependencies are so complex and vague - we probably
    do not want to be building a full abstraction model over Debian, Red Hat,
    and Windows packaging, for example - a L{Providence} represents a fully
    abstract "thing" that might be provided or depended upon for some github
    actions yaml step to take place.  By using an object here and not a string,
    we at least require the thing-being-provided to have an explicit, shared
    name that will make it harder to typo.
    """

    name: str
    doc: str


coverageData = Providence(
    "coverage-data",
    """
    Coverage data has been generated by some tests that run under
    `coverage.py`.
    """,
)
coverageSetup = Providence(
    "coverage-setup",
    """
    Coverage has been set up in the environment somehow, and any previous
    coverage data has been cleared.
    """,
)


@dataclass
class ActionsYamlFragments:
    # obviously this set of steps should be more structured, not just dicts
    steps: list[dict[str, Any]]

    # don't love using `str` here, better would be to have some code-level name
    # to point at, so perhaps these things shouldn't just be functions floating
    # around, but I digress
    provides: list[Providence] = field(default_factory=list)
    requires: list[Providence] = field(default_factory=list)


def runTrialTestsSomehow() -> ActionsYamlFragments:
    """
    1. We need to have a priority of some kind to order "Test" relative to,
       e.g. happen-after dep installation, happen-before coverage reporting

    2. the existence of $${{ matrix.tox-wrapper }} implies a dependnecy on
       a matrix axis that specifies a tox-wrapper field.  we should be
       referencing it explicitly here.

    3. same for ${{ matrix.trial-target }}
    """
    return ActionsYamlFragments(
        steps=[
            {
                "name": "Test",
                "run": "${{ matrix.tox-wrapper }} tox ${{ matrix.trial-target }}",
            }
        ],
        provides=[coverageData],
    )


def doCoverageSetup() -> ActionsYamlFragments:
    """
    this highlights the need to address multiple layers here, i.e.: how do we
    get `coverage` itself installed, if the thing installing it is going to be
    `pip` via `tox` or maybe `nox` rather than github actions?  something needs
    to be more abstract...

    additionally, different projects are going to need different ways to set
    this up, in order to be able to migrate from whatever else they were doing
    before they adopted testahedron, even at the most basic level:

        1. coverage might be installed imperatively, while not being a
           dependency at all

        2. coverage might be installed via a dev optional dependency group

        3. coverage might be installed (legacy, I guess) via a dev extra

        4. coverage might just be a straight dependency in pyproject.toml;
           probably a mistake, but, for something like a dev tool, maybe not

    coverage might also be installed via deps listed in tox.ini or noxfile.py;
    if we're going to step in and generate those files, then we don't need to
    provide a pivot point for configuration there, but we would still need to
    document it.
    """
    return ActionsYamlFragments(
        steps=[
            {
                "name": "Prepare coverage environment",
                "run": "coverage erase",
            }
        ],
        provides=[coverageSetup],
    )


def doCoverageReport() -> ActionsYamlFragments:
    return ActionsYamlFragments(
        steps=[
            {
                "name": "Prepare coverage results",
                # if: ${{ !cancelled() && !matrix.skip-coverage }}
                "run": """
                # sub-process coverage are generated in separate files so we combine them
                # to get an unified coverage for the local run.
                python -m coverage combine
                python -m coverage xml -o coverage.xml -i

                # It is important to keep the unique names for the coverage files
                # so that when uploaded to the same artifact, they don't overlap.
                # We don't combine the files yet.
                # The files from all jobs will be combined later.
                # We still do a initial combine for each job as otherwise
                # we wil end up with many files and it will take a long time
                # to upload/download/combine them.

                mv .coverage .coverage-job-${{ matrix.python-version || env.DEFAULT_PYTHON_VERSION }}-$}{{ matrix.job-name || 'default-tests' }}

                # ^^^^^^^ all of this matrix.whatever stuff needs to be
                # injected explicitly, so that everything agrees on the names
                # being used and we can detect problems with missing data
                # dependencies at the time we are compiling the yaml file
                # rather than having everything being failed builds at runtime
                """,
            }
        ],
        requires=[coverageData],
    )


@dataclass
class ActionsYamlGenerator:
    """
    This would live in the framework somewhere.
    """

    matrix: Matrix
    # These callables should be requesting dependency injection from the matrix
    # somehow?  Or from each other?
    contributors: Sequence[Callable[..., ActionsYamlFragments]]

"""
We want to generate some github actions yaml so that the matrix include/exclude
stuff is based on our common set of matrix-defined supported-environment
characteristics in the axes.

We want to use github actions' native matrix expansion, at least, the native
matrix 'include:' feature, to present a legible list of jobs in the UI.
"""
ActionsYamlGenerator(
    matrix, [runTrialTestsSomehow, doCoverageSetup, doCoverageReport]
)

"""
For tox, we want to generate some tox.toml.  However, we don't care about tox's
native matrix expansion because U{tox doesn't care about that
<https://tox.wiki/en/4.32.0/config.html#ini-only>}.  From its docs: "You should
use TOML unless you need some of the more advanced features that TOML does not
support (such as conditional factors)".  While PRs to add these features are
explicitly welcomed, the fact that TOML is suggested as the preferred options
I{before} any of these were added suggests a limited audience for them.
Furthermore, debugging tox conditional factor expansion is extremely annoying.

However, tox does provide 3 important features:

    1. consistency between CI and local environments

    2. parallel execution, which can speed up local testing considerably

    3. virtual environment isolation when building with a large number of
       environments

The goal here would be to have a way to always run all the environments you can
reasonably provision locally, in parallel, as fast as possible.  The problem of
using tox directly that we should try to solve is that running tox directly via
something like `tox -r -p auto` currently results in either under-testing
(skipping environments that might not be universally availabe) or over-testing
(trying to run Windows tests on Linux, etc).

We still want separate tox environments for virtual environment isolation, but
we don't care about massive amounts of repetition in the generated output file,
in the way that we would for github actions.  Environments will simply repeat
all their commands so we can tightly and explicitly control what gets run
without worrying about debugging tox's own conditional factor evaluation, or
attempting to hack in platform detection that runs as part of every job and
produces misleading 'pass' messages.
"""

@dataclass
class ToxTomlGenerator:
    matrix: Matrix


